import book from "../../assets/All-Books/book1.jpg"

const booksData = [
    {
      id: 1,
      booktitle: "The Great Gatsby",
      author: "F. Scott Fitzgerald",
      image: book,
      price: 10.0,
    },
    {
      id: 2,
      booktitle: "To Kill a Mockingbird",
      author: "Harper Lee",
      image: book,
      price: 10.5,
    },
    {
      id: 3,
      booktitle: "1984",
      author: "George Orwell",
      image: book,
      price: 11.0,
    },
    {
      id: 4,
      booktitle: "Pride and Prejudice",
      author: "Jane Austen",
      image: book,
      price: 11.5,
    },
    {
      id: 5,
      booktitle: "The Catcher in the Rye",
      author: "J.D. Salinger",
      image: book,
      price: 12.0,
    },
    {
      id: 6,
      booktitle: "The Hobbit",
      author: "J.R.R. Tolkien",
      image: book,
      price: 12.5,
    },
    {
      id: 7,
      booktitle: "The Lord of the Rings",
      author: "J.R.R. Tolkien",
      image: book,
      price: 13.0,
    },
    {
      id: 8,
      booktitle: "Harry Potter and the Sorcerer's Stone",
      author: "J.K. Rowling",
      image: book,
      price: 13.5,
    },
    {
      id: 9,
      booktitle: "The Da Vinci Code",
      author: "Dan Brown",
      image: book,
      price: 14.0,
    },
    {
      id: 10,
      booktitle: "The Shining",
      author: "Stephen King",
      image: book,
      price: 14.5,
    },
    {
      id: 11,
      booktitle: "The Hunger Games",
      author: "Suzanne Collins",
      image: book,
      price: 15.0,
    },
    {
      id: 12,
      booktitle: "The Alchemist",
      author: "Paulo Coelho",
      image: book,
      price: 15.5,
    },
    {
        id: 13,
        booktitle: "The Alchemist",
        author: "Paulo Coelho",
        image: book,
        price: 15.5,
      },
      {
        id: 14,
        booktitle: "The Alchemist",
        author: "Paulo Coelho",
        image: book,
        price: 15.5,
      },
      {
        id: 15,
        booktitle: "The Alchemist",
        author: "Paulo Coelho",
        image: book,
        price: 15.5,
      },
      {
        id: 16,
        booktitle: "The Alchemist",
        author: "Paulo Coelho",
        image: book,
        price: 15.5,
      },
      {
        id: 17,
        booktitle: "The Alchemist",
        author: "Paulo Coelho",
        image: book,
        price: 15.5,
      },
      {
        id: 18,
        booktitle: "The Alchemist",
        author: "Paulo Coelho",
        image: book,
        price: 15.5,
      },
      {
        id: 19,
        booktitle: "The Alchemist",
        author: "Paulo Coelho",
        image: book,
        price: 15.5,
      },
      {
        id: 20,
        booktitle: "The Alchemist",
        author: "Paulo Coelho",
        image: book,
        price: 15.5,
      },
      {
        id: 21,
        booktitle: "The Alchemist",
        author: "Paulo Coelho",
        image: book,
        price: 15.5,
      },
      {
        id: 22,
        booktitle: "The Alchemist",
        author: "Paulo Coelho",
        image: book,
        price: 15.5,
      },
      {
        id: 23,
        booktitle: "The Alchemist",
        author: "Paulo Coelho",
        image: book,
        price: 15.5,
      },
      {
        id: 24,
        booktitle: "The Alchemist",
        author: "Paulo Coelho",
        image: book,
        price: 15.5,
      },
      {
        id: 25,
        booktitle: "The Alchemist",
        author: "Paulo Coelho",
        image: book,
        price: 15.5,
      },
      
  ];
  export default booksData